# -*- coding: utf-8 -*-
"""Program11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ss44eA1wKojrJbgICq0JKE5o_Y6ILzd1
"""

a)exploratory dat analysis

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

"""Load the Breast Cancer dataset"""

data=load_breast_cancer()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target
print(df.head(5))
df.info()

print(df.describe)

print(df.isnull().sum())
print(df.describe())
print(df['target'].value_counts())

b)Visualization

#(1) Scatter plot
plt.figure(figsize=(8,6))
sns.scatterplot(x='mean radius',y='mean texture',hue='target',data=df)
plt.title("Scatter plot of Mean Radius vs Mean Texture")
plt.show()

#(2) Histogram
plt.figure(figsize=(8,6))
df['mean radius'].hist(bins=30)
plt.title("Histogram of Mean Radius")
plt.xlabel("Mean Radius")
plt.ylabel("Frequency")
plt.show()

#(3) Box plot
plt.figure(figsize=(8,6))
sns.boxplot(x='target',y='mean radius',data=df)
plt.title("Box plot of Mean Radius grouped by Target")
plt.show()



#(c) Implementing k-NN Classification
X=df.drop('target',axis=1)
y=df['target']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
k_values=[3,5,7,9]
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    accuracy = metrics.accuracy_score(y_test, y_pred)
    print(f"Accuracy with k={k}: {accuracy:.4f}")

